spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect

server:
  port: 9090


